#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define MAX_BUFFER 204800 
#define Baptisiyina_member 40
#define R 10
#define Rotation "Retrograde"

int main() {
// ファイル名用のバッファを用意
    char name_a[64];
    char name_e[64];

    // 数字を埋め込んでファイル名を作成
    // Baptisiyina_member が 40 なら "N40Rda10.txt" になる
    sprintf(name_a, "N%dRda%d.txt", Baptisiyina_member, R);
    sprintf(name_e, "N%dRde%d.txt", Baptisiyina_member, R);

    // 作成したファイル名で open する
    FILE *fa = fopen(name_a, "r");
    FILE *fe = fopen(name_e, "r");
    
    // 2. 出力ファイル (.plt) の作成
    FILE *fout = fopen("animation.plt", "w");

    if (fa == NULL || fe == NULL) {
        fprintf(stderr, "Error: file.txt が見つかりません。\n");
        if (fout) fclose(fout);
        if (fa) fclose(fa);
        if (fe) fclose(fe);
        return 1;
    }

    // 時間データを一時保存するためのファイル（メモリ上の仮想ファイル）
    FILE *ftemp_times = tmpfile(); 
    if (!ftemp_times) {
        fprintf(stderr, "Error: 一時ファイルを作成できません。\n");
        return 1;
    }

    printf("Generating animation.plt ...\n");

    // --- Gnuplot ヘッダー設定 ---
    fprintf(fout, "# Gnuplot Animation Script Generated by C\n");
    fprintf(fout, "reset\n");
    
    // GIFアニメーションの設定 (delayは1/100秒単位。10=0.1秒)
    fprintf(fout, "set terminal gif animate delay 10 size 900,600 optimize\n");
    fprintf(fout, "set output '%s_evolutionN%dr%d.gif'\n", Rotation, Baptisiyina_member, R);
    fprintf(fout, "\n");

    // グラフのデザイン設定
    fprintf(fout, "set grid\n");
    fprintf(fout, "set tics font 'Arial,13'\n");
    fprintf(fout, "set xlabel 'Semi-major axis a [AU]' font 'Arial,20'\n");
    fprintf(fout, "set ylabel 'Eccentricityfont' font 'Arial,20' offset 2.0,0\n");

    fprintf(fout, "set label 1 \"Retrograde Rotation\\nR = 10[m]\" at screen 0.5, 0.87 center font 'Arial,20'\n");

    // タイトルと重ならないように、グラフの余白を少し下に下げる
    //fprintf(fout, "set tmargin 5\n");

    //fprintf(fout, "set title offset 30,-6\nunset key\n");


    // ★ここがポイント: X軸の目盛りに特定の数値を追加★
    // set xtics add ("表示したい文字" 数値)
    // テキスト色を赤にして目立たせています
    fprintf(fout, "set xtics add ('2.2545' 2.2545)\n");

    // ★追加: 2.2545 AU に縦線を引く設定
    // from ... to ... : 始点と終点
    // graph 0 to graph 1 : グラフの下端から上端まで
    // nohead : 矢印にしない
    // lc rgb "red" : 赤色
    // dt 2 : 破線 (dashed type)
    // lw 2 : 線の太さ
    //fprintf(fout, "set arrow from 2.2545, graph 0 to 2.2545, graph 1 nohead lc rgb 'red' dt (10,10) lw 2\n");
    
    // 凡例を追加（必要なら）
    fprintf(fout, "set label 'J7:2/M5:9' at 2.2545, graph 0.95 center offset 0,0.5 tc rgb 'red'\n");
    
    // 軸の範囲 (元のコードの設定を維持)
    fprintf(fout, "set xrange [0.5:2.3]\n"); 
    fprintf(fout, "set yrange [0.0:1.0]\n");

    // N個の粒子に異なる色を割り当てるため
    fprintf(fout, "set palette rgbformulae 33,13,10\n");
    fprintf(fout, "unset colorbox\n"); // 右側のカラーバーは非表示（邪魔なので）
    fprintf(fout, "set cbrange [0:%d]\n", Baptisiyina_member); // 0番からN番までの色を固定
    
    // ポイントのスタイル
    fprintf(fout, "set style line 1 lc rgb 'blue' pt 7 ps 1.0\n");
    fprintf(fout, "\n");

    //曲線のスタイル (赤線) と関数の定義を追加
    fprintf(fout, "set style line 2 lw 0.01 dt 2\n");
    fprintf(fout, "set style line 3 lw 0.01\n"); 

    fprintf(fout, "mq(x) = 1 - 1.3/x\n");
    fprintf(fout, "eq(x) = 1 - 1.0/x\n");
    fprintf(fout, "eQ(x) = 1.0/x - 1\n");
    
    fprintf(fout, "\n");

    // --- データブロックの開始 ---
    fprintf(fout, "$DATA << EOD\n");

    char buf_a[MAX_BUFFER];
    char buf_e[MAX_BUFFER];
    int steps = 0;

    // データの読み込みと書き込み
    while (fgets(buf_a, MAX_BUFFER, fa) != NULL && fgets(buf_e, MAX_BUFFER, fe) != NULL) {
        
        char *ptr_a = buf_a;
        char *ptr_e = buf_e;
        char *end_a;
        char *end_e;

        // 1列目：時間 (t) を読み取る
        double t_val = strtod(ptr_a, &end_a);
        double t_e_val = strtod(ptr_e, &end_e); // eの方も時間は読み捨てるが進める

        if (ptr_a == end_a) continue; // 空行スキップ

        // 時間を一時ファイルに保存 (後で $TIMES ブロックにする)
        fprintf(ftemp_times, "%.6e\n", t_val);

        ptr_a = end_a;
        ptr_e = end_e;

        //　粒子IDのカウンター
        int particle_id = 0;

        // 2列目以降：粒子データ (a, e)
        while (1) {
            double val_a = strtod(ptr_a, &end_a);
            if (ptr_a == end_a) break; // 行末
            ptr_a = end_a;

            double val_e = strtod(ptr_e, &end_e);
            if (ptr_e == end_e) break; 
            ptr_e = end_e;

            // ファイルに書き込み (nanもそのまま書く)
            fprintf(fout, "%.6e %.6e %d\n", val_a, val_e, particle_id);
            particle_id++; // 次の粒子のためにIDを増やす
        }

        // ブロック区切り (2行の空行)
        fprintf(fout, "\n\n");
        steps++;
    }

    // --- データブロックの終了 ---
    fprintf(fout, "EOD\n\n");

    // --- 時間データブロックの作成 ---
    fprintf(fout, "$TIMES << EOD\n");
    rewind(ftemp_times); // 一時ファイルの先頭に戻る
    char time_buf[256];
    while (fgets(time_buf, sizeof(time_buf), ftemp_times) != NULL) {
        fprintf(fout, "%s", time_buf);
    }
    fprintf(fout, "EOD\n\n");
    fclose(ftemp_times);

    // --- アニメーションループ設定 ---
    fprintf(fout, "# Animation Settings\n");
    fprintf(fout, "num_steps = %d\n", steps);
    
    // 時間データを配列にロード
    fprintf(fout, "array TimeArray[num_steps]\n");
    fprintf(fout, "stats $TIMES using (TimeArray[$0+1] = $1) nooutput\n");
    fprintf(fout, "\n");
    
    // 単位変換定数 (秒 -> 年)
    fprintf(fout, "sec_in_year = 365.25 * 86400.0\n");

    fprintf(fout, "do for [i=1:num_steps] {\n");
    // 時間の計算
    fprintf(fout, "    t_sec = TimeArray[i]\n");
    fprintf(fout, "    t_yrs = t_sec / sec_in_year\n");
    fprintf(fout, "    t_myr = t_yrs / 1000000.0\n");
    
    // タイトルの更新 (例: Time: 1.50 Myr)
    fprintf(fout, "    set title sprintf('Time: %%g Years (%%.2f Myr)', t_yrs, t_myr) font ',14'\n");
    
    // プロット (indexは0始まりなので i-1)
    fprintf(fout, "    plot $DATA index (i-1) using 1:2:3 with points pt 7 ps 1.0 lc palette notitle, \\\n");
    fprintf(fout, "         mq(x) notitle with lines ls 2 dt 2, \\\n");
    fprintf(fout, "         eq(x) notitle with lines ls 3, \\\n");
    fprintf(fout, "         eQ(x) notitle with lines ls 3\n");

    fprintf(fout, "}\n");
    
    fprintf(fout, "set output\n"); // ファイルを閉じる
    fprintf(fout, "print 'Animation saved to orbit_evolution.gif'\n");

    printf("Done! 'animation.plt' generated (%d steps).\n", steps);
    printf("Run: gnuplot animation.plt\n");

    fclose(fa);
    fclose(fe);
    fclose(fout);

    return 0;
}